const spellingEnglishCharacters = [
  // numbers
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
   
  // letters  
  'alfa for a',
  'bravo for b',
  'charlie for c',
  'delta for d',
  'echo for e',
  'foxtrot for f',
  'golf for g',
  'hotel for h',
  'india for i',
  'juliet for j',
  'kilo for k',
  'lima for l',
  'mike for m',
  'november for n',
  'oscar for o',
  'papa for p',
  'quebec for q',
  'romeo for r',
  'sierra for s',
  'tango for t',
  'uniform for u',
  'victor for v',
  'whiskey for w',
  'x ray for x',
  'yankee for y',
  'zulu for z'

  /*  
  // symbols  
  'space',
  'tab',
  'point',
  'comma',
  'semicolon',
  'colon',
  'exclamation mark',
  'question mark',
  'tick',
  'backtick',
  'quotation mark',
  'apostrophe',
  'acute accent',
  'grave accent',
  'closing_inclined_quotes',
  'opening_inclined_quotes',
  'opening double quotes',
  'closing double quotes',
  'opening round bracket',
  'closing round bracket',
  'opening square bracket',
  'closing square bracket',
  'opening curly bracket',
  'closing curly bracket',
  'at sign',
  'asterisk_symbol',
  'hash',
  'percent sign',
  'vertical_bar',
  'slash',
  'backslash',
  'lira sign',
  'dollar sign',
  'ampersand',
  'caret',
  'equal sign',
  'dash',
  'plus sign',
  'grater-than sign',
  'less-then sign',
  'tilde',
  'underscore',
  'penny sign',
  'copyright sign',
  'division sign',
  'micron sign',
  'paragraph delimiter',
  'more or less sign',
  'trademark symbol',
  'section delimiter',
  'trademark sign',
  'japanese yen sign',
  'inverted question mark',
  'inverted exclamation mark'
  */
]

module.exports = { spellingEnglishCharacters }

