const spellingItalianCharacters = [
  // numbers
  'zero',
  'uno',
  'due',
  'tre',
  'quattro',
  'cinque',
  'sei',
  'sette',
  'otto',
  'nove',

  // letters
  'a come Ancona',
  'bi come Bologna',
  'ci come Cagliari',
  'di come Domodossola',
  'é come Empoli',
  'èffè come Firenze',
  'gi come Genova',
  'àcca come Hotel',
  'i come Imperia',
  'i lùnga come Jolly',
  'càppa come kursaal',
  'èllè come Livorno',
  'èmmè come Milano',
  'ènnè come Napoli',
  'ò come Otranto',
  'pi come Palermo',
  'cu come Quarto',
  'èrrè come Roma',
  'èssè come Savona',
  'ti come Torino',
  'u come Udine',
  'vu come Venezia',
  'vu dóppia come Washington',
  'ics come Xilofono',
  'ìpsilon',
  'zèta come Zara',
  'á con accento acuto',
  'à con accento grave',
  'é con accento acuto',
  'è con accento grave',
  'í con accento acuto',
  'ì con accento grave',
  'ó con accento acuto',
  'ò con accento grave',
  'ú con accento acuto',
  'ù con accento grave'
  /*
  'spazio',
  'tabulazione',
  'punto',
  'punto centrale',
  'virgola',
  'punto e virgola',
  'due punti',
  'punto esclamativo',
  'punto interrogativo',
  'virgoletta destra inclinata',
  'virgolette',
  'apostrofo',
  'accento acuto',
  'accento grave',
  'virgolette destre inclinate',
  'virgolette sinistre inclinate',
  'virgolette doppie aperte',
  'virgolette doppie chiuse',
  'parentesi tonda aperta',
  'parentesi tonda chiusa',
  'parentesi quadra aperta',
  'parentesi quadra chiusa',
  'parentesi graffa aperta',
  'parentesi graffa chiusa',
  'chiocciola',
  'simbolo asterisco',
  'simbolo cancelletto',
  'simbolo percento',
  'barra verticale',
  'barra',
  'barra retroversa',
  'simbolo valuta lira',
  'simbolo valuta dollaro',
  'simbolo e commerciale',
  'simbolo cappelletto',
  'simbolo uguale',
  'trattino',
  'simbolo più',
  'simbolo maggiore',
  'simbolo minore',
  'tilde',
  'trattino lungo',
  'sottolineato',
  'simbolo di centesimo',
  'simbolo di copyright',
  'simbolo di divisione',
  'simbolo micron',
  'delimitatore di paragrafo',
  'simbolo più o meno',
  'simbolo di marchio registrato',
  'delimitatore di sezione',
  'simbolo trademark',
  'simbolo valuta Yen Giapponese',
  'punto di domanda invertito',
  'punto esclamativo invertito',
  */
]

module.exports = { spellingItalianCharacters }

